# Generated by Django 4.0.2 on 2022-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=998944440044, max_length=20),
            preserve_default=False,
        ),
    ]
